### ISSUE TITLE
Speed results on Ultralytics YOLOv8 vs `nn.SiLU()`

### ISSUE THREAD

**Issue by glenn-jocher** [kostas1515/AGLU#2]
We haven't been able to train yet on this, but the speed results are here from https://github.com/ultralytics/ultralytics/pull/14644 in case they're useful for anyone. Measured on an M2 Macbook:

```bash
pip install ultralytics
# select activation in ultralytics.nn.modules.conv.Conv
yolo predict model=yolov8n.yaml
```

### `yolov8n.yaml` with SiLU activations

```
YOLOv8n summary (fused): 168 layers, 3,151,904 parameters, 31,920 gradients, 8.7 GFLOPs
...
Speed: 1.5ms preprocess, 43.8ms inference, 0.3ms postprocess per image at shape (1, 3, 640, 384)
```

### `yolov8n.yaml` with AGLU activations

```
YOLOv8n summary (fused): 281 layers, 3,152,018 parameters, 32,034 gradients, 8.7 GFLOPs
...
Speed: 1.2ms preprocess, 71.9ms inference, 0.3ms postprocess per image at shape (1, 3, 640, 384)
```

**Comment by kostas1515** [comment]
Hello, thank you for your interest in our work. May I ask what speed optimisations have you used, if any? Regarding the speed, one could do some tricks to make it faster such as use torch.compile() or save the probability output during the forward pass in the memory and re-use it during the backward as shown here: https://github.com/kostas1515/AGLU/blob/3f92b1341d3fae427c0d03da7b7b2bb176051466/classification/resnet_pytorch.py#L86

In my experiments, torch.compile() works well in some cases depending the network architecture, so it might be worth exploring.
